docs: add badges to readme
teletrace/teletrace pull request #1580
Opened 2023-04-25 15:09 UTC by haimrait

## What this PR does:
1. Add badges to readme
2. Add helm chart section to readme file

2023-04-25 19:36 UTC, ophiryael requested changes

2023-04-25 19:36 UTC, ophiryael commented on README.md
> +Teletrace is built from the ground up for modern applications. It is relies on open standards like OpenTelemetry. It is an easy-to-deploy scalable solution, that supports multiple storage options.
"It relies" instead of "It is relies"

2023-04-25 20:59 UTC, haimrait commented on README.md
> +Teletrace is built from the ground up for modern applications. It is relies on open standards like OpenTelemetry. It is an easy-to-deploy scalable solution, that supports multiple storage options.
grand mizer

2023-04-26 07:58 UTC, ophiryael approved these changes

2023-04-26 08:21 UTC, merged